### ISSUE TITLE
integerate optional headless chart generation with pptx output

### ISSUE THREAD

**Issue by fs-tom** [fsdonks/proc#17]
For the higher-order run pipelines, like proc.example/do-multiple-charts-from and proc.example/save-all-marathons [should be refactored btw....], create a higher-order function to emit all chart results to pptx files.  Assume a consistent layout (perhaps 2? slides per file).

**Comment by mpavlak1** [comment]
Added option ppt option to do-charts-from and do-multiple-charts from which expects a map with the keys :filename :template and :num-per-slide, where filename is the file that will be saved, template is the caa template ppt, and num-per-slide is a number [1 4].
