### ISSUE TITLE
Cleanup proc.example

### ISSUE THREAD

**Issue by fs-tom** [fsdonks/proc#8]
Migrate chart-specific functions into another ns, i.e. proc.charts, add as a requirement for ns declaration.
Add doc-strings and usage semantics for chart-specific functions.

all-chart-types get-chart-title  get-chart-interest inv-to-nums add-all-invs get-total-inventory add-inventory-to-chart sync-chart-scales  show-chart  save-jfree-chart get-theme

**Comment by mpavlak1** [comment]
moved chart function to new ns and wrote helper functions used in do-charts from to simplify the function a little
